-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               10.5.8-MariaDB-log - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table custom_blog_deepak.blogs
CREATE TABLE IF NOT EXISTS `blogs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(500) NOT NULL,
  `content` text NOT NULL,
  `created_by` int(11) unsigned NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_blogs_user_id` (`created_by`),
  CONSTRAINT `fk_blogs_user_id` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Dumping data for table custom_blog_deepak.blogs: ~0 rows (approximately)
/*!40000 ALTER TABLE `blogs` DISABLE KEYS */;
INSERT INTO `blogs` (`id`, `title`, `content`, `created_by`, `created_at`) VALUES
	(1, 'COMPENSABATUR, INQUIT, CUM SUMMIS', '<h1>COMPENSABATUR, INQUIT, CUM SUMMIS DOLORIBUS LAETITIA.</h1><p>LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. QUODCUMQUE IN MENTEM INCIDERET, ET QUODCUMQUE TAMQUAM OCCURRERET. QUAE CUM DIXISSET PAULUMQUE INSTITISSET, QUID EST? FALLI IGITUR POSSUMUS. <b>NON AUTEM HOC: IGITUR NE ILLUD QUIDEM.</b> DUO REGES: CONSTRUCTIO INTERRETE. </p><blockquote cite="HTTP://LORIPSUM.NET">FACIT IGITUR LUCIUS NOSTER PRUDENTER, QUI AUDIRE DE SUMMO BONO POTISSIMUM VELIT;</blockquote><ul><li>TERTIUM AUTEM OMNIBUS AUT MAXIMIS REBUS IIS, QUAE SECUNDUM NATURAM SINT, FRUENTEM VIVERE.</li><li>QUID EST IGITUR, CUR ITA SEMPER DEUM APPELLET EPICURUS BEATUM ET AETERNUM?</li><li>A PRIMO, UT OPINOR, ANIMANTIUM ORTU PETITUR ORIGO SUMMI BONI.</li><li>QUID CENSES IN LATINO FORE?</li></ul><pre>SIN AUTEM AD ANIMUM, FALSUM EST, QUOD NEGAS ANIMI ULLUM ESSEGAUDIUM, QUOD NON REFERATUR AD CORPUS.NEC MIHI ILLUD DIXERIS: HAEC ENIM IPSA MIHI SUNT VOLUPTATI,ET ERANT ILLA TORQUATIS.</pre><p>VIDESNE, UT HAEC CONCINANT? REGULI REICIENDAM; NON QUAM NOSTRAM QUIDEM, INQUIT POMPONIUS IOCANS; </p><h2>TU QUIDEM REDDES;</h2><p>PECCATA PARIA. <i>QUID ZENO?</i> AD EOS IGITUR CONVERTE TE, QUAESO. FRATER ET T. IN SCHOLA DESINIS. SED NE, DUM HUIC OBSEQUOR, VOBIS MOLESTUS SIM. </p><p><a href="HTTP://LORIPSUM.NET/" target="_BLANK">ET ILLE RIDENS: VIDEO, INQUIT, QUID AGAS;</a> RESTATIS IGITUR VOS; SED PLANE DICIT QUOD INTELLEGIT. QUID DE PYTHAGORA? CONSEQUENTIA EXQUIRERE, QUOAD SIT ID, QUOD VOLUMUS, EFFECTUM. </p><p>PARIA SUNT IGITUR. INVIDIOSUM NOMEN EST, INFAME, SUSPECTUM. <b>AN EIUSDEM MODI?</b> </p><ol><li>QUOS QUIDEM TIBI STUDIOSE ET DILIGENTER TRACTANDOS MAGNOPERE CENSEO.</li><li>NON ENIM QUAERO QUID VERUM, SED QUID CUIQUE DICENDUM SIT.</li><li>UNUM NESCIO, QUO MODO POSSIT, SI LUXURIOSUS SIT, FINITAS CUPIDITATES HABERE.</li><li>AT CUM DE PLURIMIS EADEM DICIT, TUM CERTE DE MAXIMIS.</li><li>CUR IGITUR EASDEM RES, INQUAM, PERIPATETICIS DICENTIBUS VERBUM NULLUM EST, QUOD NON INTELLEGATUR?</li><li>QUACUMQUE ENIM INGREDIMUR, IN ALIQUA HISTORIA VESTIGIUM PONIMUS.</li></ol><dl><dt><dfn>IDEM ADHUC;</dfn></dt><dd>QUOD NON FACERET, SI IN VOLUPTATE SUMMUM BONUM PONERET.</dd><dt><dfn>NIHIL SANE.</dfn></dt><dd>TU AUTEM NEGAS FORTEM ESSE QUEMQUAM POSSE, QUI DOLOREM MALUM PUTET.</dd><dt><dfn>AN EIUSDEM MODI?</dfn></dt><dd>HOSNE IGITUR LAUDAS ET HANC EORUM, INQUAM, SENTENTIAM SEQUI NOS CENSES OPORTERE?</dd></dl>', 1, '2023-02-15 09:06:00'),
	(2, 'CLAUDII LIBIDINI, QUI TUM ERAT SUMMO NE IMPERIO, DEDERETUR.', '<h1>CLAUDII LIBIDINI, QUI TUM ERAT SUMMO NE IMPERIO, DEDERETUR.</h1><p>LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. CUR DEINDE METRODORI LIBEROS COMMENDAS? AN EIUSDEM MODI? ALITER ENIM NOSMET IPSOS NOSSE NON POSSUMUS. ID MIHI MAGNUM VIDETUR. SI QUAE FORTE-POSSUMUS. DUO REGES: CONSTRUCTIO INTERRETE. SIN ALIUD QUID VOLES, POSTEA. UTRAM TANDEM LINGUAM NESCIO? </p><pre>ITAQUE <i>[REDACTED]</i> IN PRIMIS INGENUUS ET GRAVIS, DIGNUS ILLAFAMILIARITATE SCIPIONIS ET LAELII, PANAETIUS, CUM AD Q.NON MINOR, INQUIT, VOLUPTAS PERCIPITUR EX VILISSIMIS REBUSQUAM EX PRETIOSISSIMIS.</pre><dl><dt><dfn>NULLA ERIT CONTROVERSIA.</dfn></dt><dd>IAM ID IPSUM ABSURDUM, MAXIMUM MALUM NEGLEGI.</dd><dt><dfn>BEATUM, INQUIT.</dfn></dt><dd>MIHI VERO, INQUIT, PLACET AGI SUBTILIUS ET, UT IPSE DIXISTI, PRESSIUS.</dd></dl><ol><li>CUPIDITATES NON EPICURI DIVISIONE FINIEBAT, SED SUA SATIETATE.</li><li>OMNIA CONTRARIA, QUOS ETIAM INSANOS ESSE VULTIS.</li><li>NAM ET COMPLECTITUR VERBIS, QUOD VULT, ET DICIT PLANE, QUOD INTELLEGAM;</li><li>PRIMUM CUR ISTA RES DIGNA ODIO EST, NISI QUOD EST TURPIS?</li><li>SUMMAE MIHI VIDETUR INSCITIAE.</li><li>PRIMUM CUR ISTA RES DIGNA ODIO EST, NISI QUOD EST TURPIS?</li></ol><p>QUID DE PYTHAGORA? <a href="HTTP://LORIPSUM.NET/" target="_BLANK">SI LONGUS, LEVIS;</a> QUOD QUIDEM NOBIS NON SAEPE CONTINGIT. QUO TANDEM MODO? </p><p>TOLLENDA EST ATQUE EXTRAHENDA RADICITUS. NEGAT ESSE EAM, INQUIT, PROPTER SE EXPETENDAM. QUI ITA AFFECTUS, BEATUM ESSE NUMQUAM PROBABIS; TORQUATUS, IS QUI CONSUL CUM CN. NOS VERO, INQUIT ILLE; <b>BONUM LIBERI: MISERA ORBITAS.</b> EADEM NUNC MEA ADVERSUM TE ORATIO EST. </p><ul><li>ITAQUE PRIMOS CONGRESSUS COPULATIONESQUE ET CONSUETUDINUM INSTITUENDARUM VOLUNTATES FIERI PROPTER VOLUPTATEM;</li><li>QUOD QUIDEM IAM FIT ETIAM IN ACADEMIA.</li><li>ITAQUE EOS ID AGERE, UT A SE DOLORES, MORBOS, DEBILITATES REPELLANT.</li><li>QUA TU ETIAM INPRUDENS UTEBARE NON NUMQUAM.</li><li>SED TAMEN ENITAR ET, SI MINUS MULTA MIHI OCCURRENT, NON FUGIAM ISTA POPULARIA.</li></ul><p><a href="HTTP://LORIPSUM.NET/" target="_BLANK">HERI, INQUAM, LUDIS COMMISSIS EX URBE PROFECTUS VENI AD VESPERUM.</a> <a href="HTTP://LORIPSUM.NET/" target="_BLANK">QUIS ENIM REDARGUERET?</a> PRIMUM QUID TU DICIS BREVE? NUM QUID TALE DEMOCRITUS? PUTABAM EQUIDEM SATIS, INQUIT, ME DIXISSE. ET QUIDEM, INQUIT, VEHEMENTER ERRAT; OMNIA PECCATA PARIA DICITIS. </p><blockquote cite="HTTP://LORIPSUM.NET">QUONIAMQUE NON DUBIUM EST QUIN IN IIS, QUAE MEDIA DICIMUS, SIT ALIUD SUMENDUM, ALIUD REICIENDUM, QUICQUID ITA FIT AUT DICITUR, OMNE OFFICIO CONTINETUR.</blockquote><p><b>SUAM DENIQUE CUIQUE NATURAM ESSE AD VIVENDUM DUCEM.</b> <a href="HTTP://LORIPSUM.NET/" target="_BLANK">ITAQUE HIS SAPIENS SEMPER VACABIT.</a> SCISSE ENIM TE QUIS COARGUERE POSSIT? AT MULTIS MALIS AFFECTUS. <b>RECTE, INQUIT, INTELLEGIS.</b> QUOD CUM DIXISSENT, ILLE CONTRA. </p>', 1, '2023-02-15 09:11:00');
/*!40000 ALTER TABLE `blogs` ENABLE KEYS */;

-- Dumping structure for table custom_blog_deepak.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL DEFAULT '0',
  `email` varchar(255) NOT NULL DEFAULT '0',
  `password` varchar(255) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Dumping data for table custom_blog_deepak.users: ~0 rows (approximately)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `username`, `email`, `password`, `status`) VALUES
	(1, 'admin', 'admin@localhost.com', 'e10adc3949ba59abbe56e057f20f883e', 1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
